# generated by mBlock5 for codey & rocky
# codes make you happy
import codey, event, time, rocky

@event.start
def on_start():
    codey.display.show_image("00003c7e7e3c000000003c7e7e3c0000")
    codey.speaker.play_melody('laugh.wav')

@event.button_a_pressed
def on_button_a_pressed():
    codey.speaker.play_melody('hello.wav')
    while True:
        rocky.forward(50)
        if rocky.color_ir_sensor.is_obstacle_ahead():
            codey.speaker.play_melody('wrong.wav', True)
            rocky.backward(50, 1, straight = True)
            rocky.turn_left_by_degree(90)
            rocky.forward(50, 2, straight = True)

@event.button_b_pressed
def on_button_b_pressed1():
    rocky.stop()
    codey.speaker.play_melody('sigh.wav', True)
    codey.stop_all_scripts()

@event.button_c_pressed
def on_button_c_pressed2():
    codey.display.show_image("000c18181c0c000000000c1c18180c00")
    codey.speaker.play_melody('hello.wav', True)
    codey.display.show_image("000207070f0e080000080e0f07070200")

