# -*- coding: utf-8 -*-

hotranklist={'msg': 'success',
 'code': '200',
 'result': [{'id': 14941,
   'cnname': '山麻雀',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/85205531/',
   'maindesc': '山麻雀（英文名：Russet Sparrow，学名：Passer cinnamomeus），是雀形目雀科雀属的鸟类。又名红雀、赭麻雀、黄雀、山只只。属杂食性鸟类，主要以植物性食物和昆虫为食。在中国分布比较广。因平时栖息于山地而得名。中国见于秦岭以南地区。在分布区北部山地繁殖，秋季南迁越冬。体形近似麻雀。体长约14厘米。中国鹀类中的三道眉草鹀，也常被称为“山麻雀”。',
   'viewcount': 6685,
   'likecount': 90},
  {'id': 14127,
   'cnname': '虎皮鹦鹉',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/21349071/',
   'maindesc': '虎皮鹦鹉（学名：Melopsittacus undulatus，英文名：Budgerigar）是鹦鹉科虎皮鹦鹉属的鸟类，又名娇凤。属小型攀禽品种，原产于澳大利亚的内陆地区，野生的虎皮鹦鹉栖息于林缘、草地等处。结群活动。以植物种子等为食。繁殖期为6至次年1月。营巢于树洞中。每窝产卵4-8枚。孵化期为18天。性情活泼且易于驯养，在中国是大众最喜欢的宠物鸟之一，野生种群系国家二级保护动物。',
   'viewcount': 5395,
   'likecount': 184},
  {'id': 15317,
   'cnname': '家八哥',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/98174391/',
   'maindesc': '家八哥（英文名：Common Myna，学名：Acridotheres tristis），是雀形目椋鸟科八哥属的鸟类。英文名直译为普通八哥。无冠羽，眼周裸露皮肤黄色。原产于印度，但如今已被引进到世界各地（美洲、澳大利亚等），主要是为了降低农作区害虫的族群数量，但由于它们要和其他种类竞争产卵的所在，又会杀害小鸟，破坏鸟蛋，以及驱逐小型哺乳动物，因此在引进的同时，也降低了当地的生物多样性。',
   'viewcount': 4370,
   'likecount': 52},
  {'id': 15282,
   'cnname': '灰椋鸟',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/98370411/',
   'maindesc': '灰椋鸟（英文名：White-cheeked Starling，学名：Spodiopsar cineraceus），是雀形目椋鸟科丝光椋鸟属的鸟类。英文名直译为白颊椋鸟，俗名有杜丽雀、高粱头、管莲子、假画眉、竹雀。是适应能力非常强的鸟。因为它除喙与足呈橙红色外，全身都是灰褐色，所以叫它灰椋鸟。体长约23－25厘米，通体主要为灰褐色，头部上黑而两侧白，尾部亦白色，嘴和脚为橙色。',
   'viewcount': 3978,
   'likecount': 63},
  {'id': 15488,
   'cnname': '珠颈斑鸠',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/31595281/',
   'maindesc': '珠颈斑鸠（英文名：Spotted Dove，学名：Streptopelia chinensis），是鸽形目鸠鸽科珠颈斑鸠属的鸟类。又名鸪雕、鸪鸟、中斑、花斑鸠、花脖斑鸠、珍珠鸠、斑颈鸠、珠颈鸽、斑甲。比鸽子略小，颈部有黑白色的珠花图案，脚红色，体长约30cm。单独或成对出现，它们是温驯的鸟类。斑鸠是常见留鸟，叫声为轻柔悦耳的“咕咕咕”，清晨、黄昏、白天都可以听到珠颈斑鸠的反复鸣叫。是分布在南亚、东南亚地区以及中国南方广大地区的一种常见的斑鸠。',
   'viewcount': 3821,
   'likecount': 146},
  {'id': 13898,
   'cnname': '山斑鸠',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/92553441/',
   'maindesc': '山斑鸠（英文名：Oriental Turtle-Dove，学名：Streptopelia orientalis），是鸽形目鸠鸽科斑鸠属的鸟类。也叫山鸠、金背鸠、金背斑鸠、麒麟斑、麒麟鸠、雉鸠、棕背斑鸠、东方斑鸠、绿斑鸠、山鸽子、花翼、大花鸽、大花斑。上体具深色扇贝状羽缘，颈侧具黑白色条纹形成的图案，亚成鸟无此图案。包括两个亚种。山斑鸠分别分布在西伯利亚中部和中亚地区，冬天大部分种群会迁徙；成对或单独活动，与珠颈斑鸠在食性、活动区域、夜间栖息环境等方面基本相似。在中国，山斑鸠分布在北自黑龙江、新疆，南至西藏南部、海南的广大地区。',
   'viewcount': 3101,
   'likecount': 49},
  {'id': 15286,
   'cnname': '乌鸫',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/63371531/',
   'maindesc': '乌鸫（英文名：Eurasian Blackbird，学名：Turdus merula），是雀形目鸫科鸫属的鸟类。原乌鸫（学名：Turdus merula，英文名: Eurasian Blackbird）分为三种：<p>\u3000乌鸫(Turdus merula，Eurasian Blackbird)<p>\u3000乌鸫(Turdus mandarinus，Chinese Blackbird）<p>\u3000藏鸫(Turdus maximus，Tibetan Blackbird)<p>乌鸫虽继承英文名称，但乌鸫仅见于新疆与青海，与乌鸫相比雄鸟的黄色眼圈更为明显，雌鸟的斑纹也有一定差异。',
   'viewcount': 3092,
   'likecount': 70},
  {'id': 13851,
   'cnname': '喜鹊',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/62259711/',
   'maindesc': '喜鹊（英文名：Eurasian Magpie，学名：Pica pica），是雀形目鸦科鹊属的鸟类。据中国鸟类名录6.0，分布于新疆、西藏西部和呼伦贝尔的Pica pica更名为喜鹊。喜鹊是典型的黑白色鸟类，体形很大，羽毛大部为黑色，肩腹部为白色。喜鹊比较凶悍，不畏惧猛禽，常常驱赶进入其领地的鸟类包括猛禽，集群围攻欺负其他鸟儿。喜鹊多生活在人类聚居地区，喜食谷物、昆虫。喜鹊叫声婉转，在中国民间将喜鹊作为吉祥的象征，牛郎织女鹊桥相会的传说及画鹊兆喜的风俗在民间都颇为流行。喜鹊智商很高，根据维基百科所述，喜鹊是目前唯一通过了镜子测试（弄明白镜子里的那个像就是自己）的非哺乳动物。',
   'viewcount': 2759,
   'likecount': 87},
  {'id': 14893,
   'cnname': '白头鹎',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/99711671/',
   'maindesc': '白头鹎（英文名：Light-vented Bulbul，学名：Pycnonotus sinensis），是雀形目鹎科鹎属的鸟类。俗名白头翁、白头婆，英文名直译为淡臀鹎、中国鹎。是中国南方非常常见的雀鸟，体长约19厘米，头顶黑色，眉和枕羽呈白色，双翼橄榄绿色。老鸟的枕羽更洁白，所以又叫“白头翁”，幼鸟头橄榄色。数量丰富。性活泼、不甚畏人。杂食性，既食动物性食物，也吃植物性食物，以果树的浆果和种子为主食，并时常飞入果园偷吃果实。秋冬季节，白头鹎在进入繁殖期后会聚集在树林上喧叫，常常引起人们的注意。这种群聚的现象，到春季时就消失了。',
   'viewcount': 2724,
   'likecount': 143},
  {'id': 15275,
   'cnname': '八哥',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/147526591/',
   'maindesc': '八哥（英文名：Crested Myna，学名：Acridotheres cristatellus），是雀形目椋鸟科八哥属的鸟类。俗名普通八哥、鸲鹆了哥、鹦鹆、寒皋、鸜鹆、驾鸰、加令、凤头八哥。冠羽突出，全身黑色，翅有白斑，飞行时展开双翅可看到八字形的白斑。八哥是中国南方常见的鸟类。自陕西南部至长江以南各省，以及台湾和海南省均有分布。此外，八哥为雀形目椋鸟科八哥属鸟类的通称，主要分布于亚洲，中国有八哥、林八哥、白领八哥、灰背八哥、家八哥等。',
   'viewcount': 2680,
   'likecount': 72},
  {'id': 27201,
   'cnname': '小嘴乌鸦',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/128407791/',
   'maindesc': '小嘴乌鸦（英文名：Carrion Crow，学名：Corvus corone），是雀形目鸦科鸦属的鸟类。上背和下体灰色，余部黑色。冠小嘴乌鸦从小嘴乌鸦（Corvus corone）中分出的种（Knos et al.，2002；Dickinson，2003）。广泛分布于欧洲，在中国分布于新疆西部。',
   'viewcount': 2370,
   'likecount': 22},
  {'id': 27259,
   'cnname': '画眉',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/135932411/',
   'maindesc': '画眉（英文名：Chinese Hwamei，学名：Garrulax canorus），是雀形目噪鹛科噪鹛属的鸟类。分布于台湾。',
   'viewcount': 2178,
   'likecount': 53},
  {'id': 15415,
   'cnname': '夜鹭',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/32861471/',
   'maindesc': '夜鹭（英文名：Black-crowned Night-Heron，学名：Nycticorax nycticorax），是鹈形目鹭科夜鹭属的鸟类。水鸟，又名水洼子、灰洼子、星鸦、灰洼子、苍鳽、星鳽、夜鹰（浙江）、夜鹤、夜游鹤（海南）。数量丰富，是很常见的水鸟。头顶、后颈、枕、羽冠及背部黑色，枕部具2-3根狭白色冠羽；下体白色；翅及尾羽灰色。注意夜鹭亚成鸟全身棕色，具有纵纹和点斑，和成鸟羽色差异非常大，模样相近绿鹭。',
   'viewcount': 2070,
   'likecount': 60},
  {'id': 17850,
   'cnname': '鹊鸲',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/166748771/',
   'maindesc': '鹊鸲（英文名：Oriental Magpie-Robin，学名：Copsychus saularis），是雀形目鹟科鹊鸲属的鸟类。又名猪屎渣、吱渣、信鸟或四喜。分布于中国华南地区及长江以南一带。典型的黑白色鸟类。鹊鸲雄鸟上半部为黑色，在翼处有白斑，下体前黑后白，时常竖起尾巴，把尾翼扭向前方，在地上则常以弹跳方式前进。雌鸟上体灰色。鹊鸲与喜鹊相似，但体形细小得多。鹊鸲性格活泼好动，觅食时常摆尾，不分四季晨昏，在高兴时会在树枝或大厦外墙鸣唱。',
   'viewcount': 2009,
   'likecount': 87},
  {'id': 13964,
   'cnname': '麻雀',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/63038961/',
   'maindesc': '麻雀（英文名：Eurasian Tree Sparrow，学名：Passer montanus），是雀形目雀科雀属的鸟类。又叫树麻雀（英文名：Tree Sparrow），俗名霍雀、瓦雀、琉雀、家雀、老家贼、只只、嘉宾、照夜、麻谷、南麻雀、禾雀、宾雀，亦叫北国鸟（个别地方方言又称呼为：家雀、户巴拉）。雌雄同色，显著特征为黑色喉部、白色脸颊上具黑斑、栗色头部。喜群居，种群生命力极强。是中国最常见、分布最广的鸟类，亚种分化极多，广布于中国全境，也广布于欧亚大陆。中国产5种麻雀，其中树麻雀就是我们通常所说的麻雀，其他种类如山麻雀、家麻雀比树麻雀少见，生活环境也有所区别。',
   'viewcount': 1776,
   'likecount': 64},
  {'id': 13813,
   'cnname': '大杜鹃',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/55599051/',
   'maindesc': '大杜鹃（英文名：Common Cuckoo，学名：Cuculus canorus），是鹃形目杜鹃科杜鹃属的鸟类。俗名布谷鸟、郭公、布谷、喀咕。分布于北极圈以外的欧洲、非洲、亚洲，包括中国大陆的中国等地，多栖息于山地及平原的树上以及居民点附近。该物种的模式产地在瑞典。中国有“望帝春心托杜鹃”的神话故事。具有巢寄生的繁殖特点。叫声为两个音节“布谷”或“布谷-布谷”。',
   'viewcount': 1715,
   'likecount': 42},
  {'id': 13899,
   'cnname': '棕背伯劳',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/94956501/',
   'maindesc': '棕背伯劳（英文名：Long-tailed Shrike，学名：Lanius schach），是雀形目伯劳科伯劳属的鸟类。俗称桂来姆、黄伯劳，英文名直译为长尾伯劳。棕背伯劳特征是粗黑的贯眼纹或顶冠、黑翅、尾长尾黑，上体偏灰，下体偏棕。普遍分布于我国东部沿海及南部，包括台湾、海南等省，是一种很常见的留鸟。伯劳性凶猛，嘴爪均强健有力，善于捕食昆虫、鸟类及其他动物，甚至能击杀比它自己还大的鸟，如鹧鸪之类。90年代在中国江西发现的黑伯劳，被认为是棕背伯劳的黑色型，不足以列为独立鸟种。',
   'viewcount': 1644,
   'likecount': 66},
  {'id': 27314,
   'cnname': '灰喜鹊',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/98785381/',
   'maindesc': '灰喜鹊（英文名：Azure-winged Magpie，学名：Cyanopica cyanus），是雀形目鸦科灰喜鹊属的鸟类。又名山喜鹊、蓝鹊、蓝膀香鹊、长尾鹊、鸢喜鹊、长尾巴郎。顶冠黑色，两翼及尾天蓝色，余部灰色。灰喜鹊在中国分布较广泛，是常见的鸦类，体型比喜鹊小，性吵嚷，结群栖于开阔松林及阔叶林、公园甚至城镇。飞行时振翼快，作长距离的无声滑翔。在树上、地面及树干上取食，食物为果实、昆虫及动物尸体。该物种是国家三有保护鸟类，安徽省的省鸟。',
   'viewcount': 1596,
   'likecount': 51},
  {'id': 13800,
   'cnname': '白胸翡翠',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/43773481/',
   'maindesc': '白胸翡翠（英文名：White-throated Kingfisher，学名：Halcyon smyrnensis），是佛法僧目翠鸟科翡翠属的鸟类。也叫白喉翡翠。嘴赤红，头颈和腹部栗色，胸部白色。是一种分布在亚洲南部和西部的翡翠。同大多数猎翠鸟一样，完全是肉食性。白胸翡翠在软石面掘洞为巢，多离水道甚远，繁殖期为4-6月。',
   'viewcount': 1557,
   'likecount': 16},
  {'id': 14589,
   'cnname': '费氏牡丹鹦鹉',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/63736361/',
   'maindesc': '费氏牡丹鹦鹉费氏牡丹鹦鹉（学名：Agapornis fischeri，英文名：Fischer’s Lovebird）是鹦鹉科牡丹鹦鹉属的鸟类，又叫牡丹鹦鹉、费氏情侣鹦鹉、费氏爱情鸟。是七彩缤纷的小鹦，国内现有9个品种，为较珍贵的人工繁育鸟。常见的品种有琉璃腰牡丹鹦鹉(棕头牡丹鹦鹉)、黄领黑牡丹鹦鹉(黑头牡丹鹦鹉)、金红桃牡丹鹦鹉(桃脸黄牡丹鹦鹉)、小樱哥牡丹鹦鹉(桃脸绿牡丹鹦鹉)及蓝牡丹鹦鹉等品种。牡丹鹦鹉性情凶猛，以强欺弱，发情雌鸟更为突出，叫声大而杂，有时噪声扰人，还可向其他鸟进攻，这时若将雌鸟与雄鸟配对繁育则鸣声锐减，性情好转，所以饲养牡丹鹦鹉以成对为佳。经人工培养还有多种色系的品种：如黄、白、钴蓝、紫、灰、银、乳白及杂纹等。平均寿命约10–15年。分布于非洲中南部地区坦桑尼亚以北，维多利亚湖附近之草原，是近危物种。',
   'viewcount': 1545,
   'likecount': 47}]}

recommendlist={'msg': 'success',
 'code': '200',
 'result': [{'id': 27016,
   'cnname': '台湾斑翅鹛',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/59337771/',
   'maindesc': '台湾斑翅鹛（英文名：Taiwan Barwing，学名：Actinodura morrisoniana），是雀形目噪鹛科斑翅鹛属的鸟类。台湾特有种。体型略大的褐色鹛。羽冠蓬松，头侧深栗，上背及腰灰，喉红栗。背中部红褐，胸橄榄褐而具浅色纵纹。腹部及臀棕褐。翼及尾具黑色横斑，尾端白色。',
   'viewcount': 14,
   'likecount': 0,
   'rId': 0},
  {'id': 27018,
   'cnname': '灰头斑翅鹛',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/130835201/',
   'maindesc': '灰头斑翅鹛（英文名：Streaked Barwing，学名：Actinodura souliei），是雀形目噪鹛科斑翅鹛属的鸟类。体大(22厘米)而羽冠蓬松的鹛。体羽多鳞斑。眼先及脸颊前部黑色。冠羽和耳覆羽浅灰。头侧深栗，喉红栗。上背、背、腰、腹及臀部的羽毛黑色，羽缘黄褐而成矛状纹。翼及尾栗色而带细小的黑色横斑。分布于云南、四川。',
   'viewcount': 12,
   'likecount': 0,
   'rId': 0},
  {'id': 27019,
   'cnname': '纹头斑翅鹛',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/144464161/',
   'maindesc': '纹头斑翅鹛（英文名：Hoary-throated Barwing，学名：Actinodura nipalensis），是雀形目噪鹛科斑翅鹛属的鸟类。中等体型(21厘米)的深褐色鹛。两翼及长尾具黑色细小横斑。与其他斑翅鹛的区别在带羽冠的头部多具皮黄色细纵纹。头侧灰色，眼圈狭窄而偏白，髭纹黑色。尾具黑色的端带。下体浅褐灰，至腹部成红棕色。',
   'viewcount': 5,
   'likecount': 0,
   'rId': 0},
  {'id': 27013,
   'cnname': '长尾奇鹛',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/80071011/',
   'maindesc': '长尾奇鹛（英文名：Long-tailed Sibia，学名：Heterophasia picaoides），是雀形目噪鹛科奇鹛属的鸟类。体大的灰色及白色树栖型奇鹛。尾甚长而尖。体羽暗灰。分布于尼泊尔、锡金、不丹、印度、孟加拉、缅甸、老挝、泰国、越南、马来半岛、印度尼西亚以及中国大陆的云南等地，多见于海拔915-2440米间的山脚地带以及常绿阔叶林或山坡阔叶林。该物种的模式产地在尼泊尔。',
   'viewcount': 76,
   'likecount': 1,
   'rId': 0},
  {'id': 27014,
   'cnname': '灰奇鹛',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/40080841/',
   'maindesc': '灰奇鹛（英文名：Gray Sibia，学名：Heterophasia gracilis），是雀形目噪鹛科奇鹛属的鸟类。顶冠及头侧深灰，脸近黑，喉及胸偏白。分布于印度、缅甸以及中国大陆的云南等地，多生活于山坡、村边的小阔叶树上、在海拔较高的地区以及常在松树的顶端活动。栖于山坡阔叶林间。结小群活动。以昆虫和植物种子为食。该物种的模式产地在印度阿萨姆邦。该物种已被列入国家林业局2000年8月1日发布的《国家保护的有益的或者有重要经济、科学研究价值的陆生野生动物名录》。',
   'viewcount': 12,
   'likecount': 0,
   'rId': 0},
  {'id': 27015,
   'cnname': '褐脸雀鹛',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/94385771/',
   'maindesc': '褐脸雀鹛（英文名：Brown-cheeked Fulvetta，学名：Alcippe poioicephala），是雀形目幽鹛科雀鹛属的鸟类。体大(16厘米)的褐色雀鹛。顶冠及颈背灰色，具黑色的长眉纹，下体皮黄色。与灰眶雀鹛及白眶雀鹛的区别为脸颊暖褐色，无白色眼圈且体型较大。',
   'viewcount': 19,
   'likecount': 0,
   'rId': 0},
  {'id': 27010,
   'cnname': '白眉歌鸫',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/81164131/',
   'maindesc': '白眉歌鸫（英文名：Redwing，学名：Turdus iliacus），是雀形目鸫科鸫属的鸟类。是原住于欧洲及亚洲的一种鸫，比相关的欧歌鸫较为细小。它们最特别的是两侧及翼底呈红色，眼睛上有奶白色斑纹，故以“白眉”为名。白眉歌鸫在中国境内比较罕见，偶有越冬鸟至新疆西北部的阿尔泰山，是土耳其的国鸟。',
   'viewcount': 256,
   'likecount': 4,
   'rId': 0},
  {'id': 27011,
   'cnname': '田鸫',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/58813401/',
   'maindesc': '田鸫（英文名：Fieldfare，学名：Turdus pilaris），是雀形目鸫科鸫属的鸟类。体型略大(26厘米)的鸫。灰色的头及腰部与栗褐色的背部成对比，下体白，胸及两胁满布黑色纵纹.',
   'viewcount': 79,
   'likecount': 2,
   'rId': 0},
  {'id': 27012,
   'cnname': '丽色奇鹛',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/142723601/',
   'maindesc': '丽色奇鹛（英文名：Beautiful Sibia，学名：Heterophasia pulchella），是雀形目噪鹛科奇鹛属的鸟类。是海拔迁徙的候鸟，分布于印度、缅甸和中国大陆。该物种的保护状况被评为无危。丽色奇鹛的平均体重约为41.0克。栖息地为亚热带或热带的湿润山地林。该物种的模式产地在印度。',
   'viewcount': 28,
   'likecount': 2,
   'rId': 0},
  {'id': 27007,
   'cnname': '黑冠黄鹎',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/85684431/',
   'maindesc': '黑冠黄鹎（英文名：Black-crested Bulbul，学名：Rubigula flaviventris），是雀形目鹎科鹎属的鸟类。',
   'viewcount': 87,
   'likecount': 3,
   'rId': 0},
  {'id': 27008,
   'cnname': '锈腹短翅鸫',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/118184891/',
   'maindesc': '锈腹短翅鸫（英文名：Rusty-bellied Shortwing，学名：Brachypteryx hyperythra），是雀形目鹟科短翅鸫属的鸟类。是体长约13厘米的短翅鸫。特征为上体蓝灰，下体深铁锈色。细小的眉纹白色（部分被掩盖），眼先黑色。雌鸟：上体橄榄褐色，下体浅铁锈色，腹中心白色。甚不惧人。栖居林下密丛。分布于印度、锡金以及中国大陆的云南等地，一般生活于地面、见于以栎树为主的常绿阔叶林以及喜在密林下木、灌木丛或竹丛间活动。',
   'viewcount': 29,
   'likecount': 2,
   'rId': 0},
  {'id': 27009,
   'cnname': '白喉短翅鸫',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/79864741/',
   'maindesc': '白喉短翅鸫（英文名：Lesser Shortwing，学名：Brachypteryx leucophris），是雀形目鹟科短翅鸫属的鸟类。一种体甚小而腿长的短翅鸫，约13厘米长，外形和画眉鸟相似。它是一种杂食性卵生鸟类，性羞怯。',
   'viewcount': 62,
   'likecount': 5,
   'rId': 0},
  {'id': 27004,
   'cnname': '白喉冠鹎',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/142725291/',
   'maindesc': '白喉冠鹎（英文名：White-throated Bulbul，学名：Alophoixus flaveolus），是雀形目鹎科冠鹎属的鸟类。体型略大(22厘米)而具羽冠的褐色鹎。白色的喉膨起，下体黄色。似白喉冠鹎但较鲜亮，上体褐色较重，腹部为鲜亮的柠檬黄色。',
   'viewcount': 107,
   'likecount': 3,
   'rId': 0},
  {'id': 27005,
   'cnname': '白颊鹎',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/96056311/',
   'maindesc': '白颊鹎（英文名：Himalayan Bulbul，学名：Pycnonotus leucogenys），是雀形目鹎科鹎属的鸟类。中等体型，是鹎科的一种鸣禽。分布在阿富汗、不丹、印度、塔吉克斯坦及沙特阿拉伯等地区。白颊鹎雏鸟若与人一起生活，则会变得对人类友善。是巴林的国鸟。',
   'viewcount': 378,
   'likecount': 12,
   'rId': 0},
  {'id': 27006,
   'cnname': '黑头鹎',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/143687661/',
   'maindesc': '黑头鹎（英文名：Black-headed Bulbul，学名：Brachypodius atriceps），是雀形目鹎科鹎属的鸟类。分布于印度、孟加拉、中南半岛、印度尼西亚、菲律宾以及中国大陆的云南等地，多见于乔木枝头。该物种的模式产地在印度尼西亚苏门答腊。',
   'viewcount': 426,
   'likecount': 8,
   'rId': 0},
  {'id': 26997,
   'cnname': '白冠攀雀',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/44930351/',
   'maindesc': '白冠攀雀（英文名：White-crowned Penduline-Tit，学名：Remiz coronatus），是雀形目攀雀科攀雀属的鸟类。小型鸟类。分布于中亚至中国西北及俄罗斯东南部。一般栖息于近水的苇丛和柳、桦、杨等阔叶树间。主要以昆虫为食，也吃植物的叶，花，芽，花粉和汁液。捕获猎物的方式和一般的山雀相同。冬季结群，通常比其他攀雀更喜栖于树上。',
   'viewcount': 54,
   'likecount': 5,
   'rId': 0},
  {'id': 26998,
   'cnname': '金冠树八哥',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/89715231/',
   'maindesc': '金冠树八哥（英文名：Golden-crested Myna，学名：Ampeliceps coronatus），是雀形目椋鸟科金冠树八哥属的鸟类。分布于印度、缅甸、泰国以及中国大陆的云南、广东等地。该物种的模式产地在缅甸德林达依省。',
   'viewcount': 136,
   'likecount': 2,
   'rId': 0},
  {'id': 27000,
   'cnname': '黄眉林雀',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/44576741/',
   'maindesc': '黄眉林雀（英文名：Yellow-browed Tit，学名：Sylviparus modestus），是雀形目山雀科黄眉林雀属的鸟类。体小(10厘米)而异型的山雀。外形似柳莺或啄花鸟。体羽大致橄榄色，羽冠短，狭窄的黄色眼圈，浅黄色短眉纹有时被覆盖；腿甚显粗壮。与火冠雀的区别在具冠羽而腰部无浅色反差。该物种的模式产地在尼泊尔。',
   'viewcount': 72,
   'likecount': 3,
   'rId': 0},
  {'id': 26994,
   'cnname': '双辫八色鸫',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/32073311/',
   'maindesc': '双辫八色鸫（英文名：Eared Pitta，学名：Hydrornis phayrei），是雀形目八色鸫科蓝八色鸫属的鸟类。分布于中国西南部及东南亚。为世界濒危物种其中一种，是联合国《濒危野生动物名录》其中之一。',
   'viewcount': 74,
   'likecount': 3,
   'rId': 0},
  {'id': 26995,
   'cnname': '栗头八色鸫',
   'coveraddress': 'https://download.ams.birds.cornell.edu/api/v1/asset/142168811/',
   'maindesc': '栗头八色鸫（英文名：Rusty-naped Pitta，学名：Hydrornis oatesi），是雀形目八色鸫科蓝八色鸫属的鸟类。体型圆胖，尾短，腿长，常在森林底层或低植被中找食无脊椎动物。叫声简单哀婉。头部栗褐色；前额、两颊、颈侧、喉至上胸渲染粉红色；上体、尾表暗绿，腰沾蓝色，上背栗褐色。下体茶黄，肛周呈棕白色。上嘴黑色，下嘴黄褐色；眼虹膜棕红或红褐色；跗蹠灰白色或角褐色。主要栖息在海拔1800米以下的热带、亚热带的常绿阔叶林中，单个或成对在林下阴湿处活动觅食，喜在夜间鸣叫。主要以昆虫为食，也兼吃种子和果实。分布于中南半岛，中国的东南沿海地区和太平洋诸岛屿。',
   'viewcount': 26,
   'likecount': 2,
   'rId': 0}]}